name: Automate with ChatGPT

on:
  pull_request:
    branches:
      - feature/automate-with-chatgpt
    paths:
      - '**.js'

jobs:
  evaluate_code:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 8.1.2

    - name: Install Yarn
      run: npm install -g yarn@1.22.19

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Get pull request diff
      id: get_diff
      run: |
        git fetch origin ${{ github.base_ref }}
        git diff --unified=0 FETCH_HEAD..HEAD > pr_diff.txt

    - name: Post comment using Node.js script
      run: node chatgpt-scripts.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.number }}
